In [1]:
#Dependencies
from splinter import Browser
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import requests

In [2]:
#1941 Billboard
url41 = 'http://billboardtop100of.com/1941-2/'

In [3]:
tables41 = pd.read_html(url41)

In [4]:
tables41[0]

     0                    1                                      2
0    1         Glenn Miller                  Chattanooga Choo Choo
1    2           Sammy Kaye                                  Daddy
2    3           Artie Shaw                               Stardust
3    4  The Andrews Sisters                Boogie Woogie Bugle Boy
4    5         Jimmy Dorsey          Amapola (Pretty Little Poppy)
..  ..                  ...                                    ...
75  76            Kay Kyser              (Lights Out) Til Reveille
76  77          Tony Martin              The Last Time I Saw Paris
77  78         Tommy Tucker  I Don’t Want to Set the World On Fire
78  79         Guy Lombardo        Intermezzo (Souvenir De Vienne)
79  80     Anjos do Inferno                   Voce Ja Foi a Bahia?

[80 rows x 3 columns]

In [5]:
df41 = tables41[0]

In [6]:
pd.DataFrame.to_csv(df41, 'top41.csv')

In [7]:
#1945 Billboard
url45 = 'http://billboardtop100of.com/1945-2/'
tables45 = pd.read_html(url45)
tables45[0]

,0,1,2
0,1,The Andrews Sisters,Rum & Coca-Cola
1,2,Les Brown,Sentimental Journey
2,3,Perry Como,Till The End of Time
3,4,Les Brown,My Dreams Are Getting Better All the Time
4,5,Johnny Mercer,"On the Atchison, Topeka & the Santa Fe"
...,...,...,...
75,76,Hal McIntyre & his Orchestra,Sentimental Journey
76,77,Johnny Long,My Dreams Are Getting Better All the Time
77,78,Betty Grable,I Can’t Begin to Tell You
78,79,Gilberto Alves,Prece a Lua
79,80,Dizzy Gillespie,Salt Peanuts

In [14]:
df45 = tables45[0]

In [15]:
pd.DataFrame.to_csv(df45, 'top45.csv')

In [8]:
#1950 Billboard
url50 = 'http://billboardtop100of.com/1950-2/'
tables50 = pd.read_html(url50)
tables50[0]

,0,1,2
0,1,Gordon Jenkins and The Weavers,Goodnight Irene
1,2,Nat King Cole,Mona Lisa
2,3,Anton Karas,Third Man Theme
3,4,Gary and Bing Crosby,Sam’s Song
4,5,Gary and Bing Crosby,Simple Melody
5,6,Teresa Brewer,"Music, Music, Music"
6,7,Guy Lombardo,Third Man Theme
7,8,Red Foley,Chattanoogie Shoe Shine Boy
8,9,Sammy Kaye,Harbor Lights
9,10,Sammy Kaye and Don Cornell,It Isn’t Fair
10,11,Eileen Barton,If I Knew You Were Coming I’d’ve Baked A Cake
11,12,Kay Starr,Bonaparte’s Retreat
12,13,Gordon Jenkins and The Weavers,"Tzena, Tzena, Tzena"
13,14,Tony Martin,There’s No Tomorrow
14,15,Phil Harris,The Thing
15,16,Ames Brothers,Sentimental Me
16,17,Andrews Sisters and Gordon Jenkins,I Wanna Be Loved
17,18,Patti Page,Tennessee Waltz
18,19,Andrews Sisters and Gordon Jenkins,"I Can Dream, Can’t I"
19,20,Tennessee Ernie Ford and Kay Starr,I’ll Never Be Free
20,21,Patti Page,All My Love
21,22,Gordon Jenkins,My Foolish Heart
22,23,Ames Brothers,Rag Mop
23,24,Bill Snyder,Bewitched
24,25,Perry Como,Hoop-Dee-Doo
25,26,Gordon Jenkins,Bewitched
26,27,Ames Brothers,Can Anyone Explain?
27,28,Billy Eckstine,My Foolish Heart
28,29,Bing Crosby,Dear Hearts And Gentle People
29,30,Frankie Laine,Cry Of The Wild Goose

In [9]:
df50 = tables50[0]

In [10]:
pd.DataFrame.to_csv(df50, 'top50.csv')

In [16]:
#1955 Billboard
url55 = 'http://billboardtop100of.com/1955-2/'
tables55 = pd.read_html(url55)
tables55[0]

     0                                 1                                    2
0    1                       Perez Prado  Cherry Pink And Apple Blossom White
1    2         Bill Haley and His Comets                Rock Around The Clock
2    3                      Mitch Miller             The Yellow Rose Of Texas
3    4                    Roger Williams                        Autumn Leaves
4    5                        Les Baxter                     Unchained Melody
5    6                        Bill Hayes          The Ballad Of Davy Crockett
6    7                         Four Aces      Love Is A Many Splendored Thing
7    8                   McGuire Sisters                            Sincerely
8    9                         Pat Boone                   Ain’t That A Shame
9   10                     Georgia Gibbs                  Dance With Me Henry
10  11                        Crazy Otto             Crazy Otto Medley I & 11
11  12                      Billy Vaughn                       Melody Of Love
12  13              Tennessee Ernie Ford                         Sixteen Tons
13  14                     Frank Sinatra                   Learnin’ The Blues
14  15                  Fontaine Sisters                      Hearts Of Stone
15  16                     Georgia Gibbs                          Tweedle Dee
16  17                         Four Lads                  Moments To Remember
17  18                        Chordettes                          Mr. Sandman
18  19                        Joan Weber                      Let Me Go Lover
19  20                     Nat King Cole                       A Blossom Fell
20  21                        Al Hibbler                     Unchained Melody
21  22                       Fess Parker          The Ballad Of Davy Crockett
22  23                        Art Mooney                           Honey Babe
23  24              Tennessee Ernie Ford          The Ballad Of Davy Crockett
24  25                        Perry Como                             Ko Ko Mo
25  26                  Gisele Mackenzie                          Hard To Get
26  27                     Ames Brothers       The Naughty Lady Of Shady Lane
27  28                    Jaye P. Morgan           That’s All I Want From You
28  29                          Platters                             Only You
29  30  Somethin’ Smith and The Redheads             It’s A Sin To Tell A Lie

In [17]:
df55 = tables55[0]
pd.DataFrame.to_csv(df55, 'top55.csv')

In [11]:
#1960 Billboard
url60 = 'http://billboardtop100of.com/1960-2/'
tables60 = pd.read_html(url60)
tables60[0]

      0                 1                            2
0     1       Percy Faith  Theme From “A Summer Place”
1     2        Jim Reeves             He’ll Have To Go
2     3   Everly Brothers                Cathy’s Clown
3     4    Johnny Preston                 Running Bear
4     5      Mark Dinning                   Teen Angel
..  ...               ...                          ...
95   96      Bobby Rydell            Little Bitty Girl
96   97     Barret Strong                        Money
97   98  Maurice Williams                         Stay
98   99      Charlie Rich              Lonely Weekends
99  100        Larry Hall                        Sandy

[100 rows x 3 columns]

In [12]:
df60 = tables60[0]

In [13]:
pd.DataFrame.to_csv(df60, 'top60.csv')

PermissionError: [Errno 13] Permission denied: 'top60.csv'

In [18]:
#1965 Billboard
url65 = 'http://billboardtop100of.com/1965-2/'
tables65 = pd.read_html(url65)
tables65[0]

,0,1,2
0,1,Sam The Sham and The Pharaohs,Wooly Bully
1,2,Four Tops,I Can’t Help Myself (Sugar Pie Honey Bunch)
2,3,Rolling Stones,(I Can’t Get No) Satisfaction
3,4,We Five,You Were On My Mind
4,5,Righteous Brothers,You’ve Lost That Lovin’ Feelin’
...,...,...,...
95,96,Jack Jones,The Race Is On
96,97,"Dino, Desi and Billy",I’m A Fool
97,98,Ad Libs,The Boy From New York City
98,99,Del Shannon,Keep Searchin’
99,100,Marvin Gaye,How Sweet It Is (To Be Loved By You)

In [20]:
df65 = tables65[0]
pd.DataFrame.to_csv(df65, 'top65.csv')